name: Build and push the edge image

on:
    push:
        branches:
            - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    run-pre-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 18
            - run: |
                  sudo bash -c "mkdir /captain && chown -R `whoami` /captain"
                  npm ci
                  npm run build
                  npm run lint
                  npm run formatter
                  npm run test
    build-publish-github-image:
        needs: run-pre-checks
        runs-on: ubuntu-latest
        steps:
            - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/checkout@v1
            - name: Build and Push Edge to Github CR
              shell: bash
              run: ./dev-scripts/build_and_push_edge.sh
